### PR TITLE
#247

### PR DESCRIPTION
**Pull request by KorDum**
#247
Fix database doesn't show species name
Fix layout of breeder page

### CODE REVIEW

**Comment by KorDum** [comment]
@mezz Can you upload new version of mod on Curse? =)

**Comment by mezz** [comment]
Released here: https://minecraft.curseforge.com/projects/binnies-mods/files/2460776

**Comment by mezz** [comment]
Please write more descriptive names for PRs like this one in the future, because they are used to generate the changelog.

**Comment by mezz** [comment]
Nevermind the naming, it looks like the changelog script picked up the additional lines just fine.

**Pull request merged**
