### PR TITLE
Fix ru_RU.lang in genetics/lang/ru_RU.lang

### PR DESCRIPTION
**Pull request by RusTit**

### CODE REVIEW

**Comment by KorDum** [comment]
@mezz looks like OK =)

**Comment by RusTit** [comment]
Hi, my fix is correct (in general).
But also need some changes in this file.
binnie/core/machines/MachinePackage.java
Relative path to "Title" and "Tooltip" is combined wrong (sorry for my English).
For example:
Now all machine names use this key
(genetics.machine.lab_machine.analyser)
But code create this
(genetics.lab_machine.analyser)
At current stage I don't know what should be better (update method getDisplayName and getInformation) or update localisation

**Comment by RusTit** [comment]
Some examples (latest and original binnie jar):
`genetics.machine.lab_machine.analyser=Analyzer`
`genetics.machine.lab_machine.analyser.info=The Analyzer takes breedable individuals and DNA sequencers and analyzes them to determine the genes present. This requires DNA Dye, created from purple dye and glowstone`
analyser
`genetics.machine.lab_machine.lab_machine=Lab Stand`
`genetics.machine.lab_machine.lab_machine.info=`
lab_machine
Splicer info work because using this path (genetics.adv_machine.splicer.info) - no "machine"
`genetics.machine.adv_machine.splicer=Splicer`
`genetics.adv_machine.splicer.info=The Splicer is an incredibly powerful machine that is used to insert genes into individuals. This process is fast, but requires monumental amounts of power.`
splicer

**Comment by RusTit** [comment]
screenshot_20180306_214300
screenshot_20180306_214323
Latest commit is fixing path resolving for localized strings

**Comment by RusTit** [comment]
Another commit for fixing storage title
screenshot_20180306_214854
screenshot_20180306_215121

**Comment by RusTit** [comment]
#383

**Comment by mezz** [comment]
Thanks!

**Pull request merged**
