### PR TITLE
Messages about the error-deprecated method are suppressed in core/src/main/java/binnie/core/machines/BlockMachine.java.

### PR DESCRIPTION
**Pull request by RusTit**
I want to update the code to remove all possible errors and warnings.
Decided to fix deprecated methods.
As indicated,
including in this topic,
http://www.minecraftforge.net/forum/topic/39491-194-deprecated-methods-in-blocks/
these messages can be easily suppressed.

### CODE REVIEW

**Comment by RusTit** [comment]
Also this topic
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2685116-so-many-deprecated-functions-whats-the

**Comment by mezz** [comment]
I don't think this is very important to do, but if it helps you then go ahead.

**Comment by RusTit** [comment]
I agree that this is not very important, it just upsets my inner perfectionist, so I started offering repository edits, including because of this.

**Comment by mezz** [comment]
That's fine, it's certainly not hurting anything.

**Pull request merged**
