### PR TITLE
Prototype: BlockLiquid

### PR DESCRIPTION
**Pull request by RusTit**
The task is not finished. DO NOT MERGE
I tried to realize this task, but before I continue, I want to clarify whether I'm doing the right thing and the right way.

### CODE REVIEW

**Comment by mezz** [comment]
Take a look at how it's implemented in Forestry for some inspiration: https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/fluids/BlockForestryFluid.java

**Comment by RusTit** [comment]
I did so.
I just found in the code an old render for a block of liquid.
And a little hesitated.

**Comment by RusTit** [comment]
In addition, is the logic of ignition necessary for Binnie liquids?

**Comment by mezz** [comment]
For rendering I think @Nedelosk will have better advice.

Lots of Binnie liquids are flammable but I don't think any are hot like lava, are they? Probably don't need that logic.

**Comment by RusTit** [comment]
It seems to me that spirit (and other in enum) can be flammable.

**Comment by mezz** [comment]
Maybe the very strong distilled liquids should be made flammable? I would look them up on wikipedia to see which ones could actually burn.

**Comment by RusTit** [comment]
I will continue to adapt the code of liquids from Forestry.
Also required are the ignition temperatures.
Not yet figured out how to expose the dynamic color of liquids.

**Comment by RusTit** [comment]
It seems to work
Need revew.

**Comment by RusTit** [comment]
Suggestion: Make fluids volatile, with the passage of time they disappearing. In nature, alcohols behave as they do. The remaining liquids are also valuable, this will help prevent them from being poured out (Paradox).

**Review by Nedelosk — APPROVED** [review]

**Review by mezz — APPROVED** [review]
Looks good to me

**Pull request merged**
