### PR TITLE
Create binnie-mods-2.0(1.7.10)-pre15-ru-u8.zs

### PR DESCRIPTION
**Pull request by lex1975**
Not all items are in the language files.
Therefore, for more complete Russification NEI and CraftTweaker script are required

### CODE REVIEW

**Comment by mezz** [comment]
Does this get automatically loaded? I've never seen a .zs file distributed inside a mod.

**Comment by Dream-Master** [comment]
@mezz its a minetweaker script which fix or add russian localizer. Its loaded from the script folder if you have minetwweaker/crafttweaker installed.
https://github.com/stanhebben/MineTweaker3

**Comment by KorDum** [comment]
I think we can accept this PR, until #30 issue is done.

**Comment by mezz** [comment]
I understand that it is a minetweaker script, but putting it here will not include it in people's script folder. 
Is there a way to have it load from the mod's jar?

**Comment by KorDum** [comment]
Basically, I already started translating the hardcode strings into localization files.
This is not a fast process and there are many places from code with this problem.

**Comment by mezz** [comment]
We can keep this here until the localization fixes are complete.

**Pull request merged**
