### PR TITLE
Fix #30

### LINKED ISSUE #30: [1.7.10] Some hardcodded localization
In all project's code. Need to wrap to localize method.

### PR DESCRIPTION
**Pull request by KorDum**
Partial fix for issue #30
Please review this after PR #52, because contains changes from #52.

Rename Binnie.Language to short Binnie.I18N.
Removed some unused methods, classes.
Removed some hardcoded strings, replaced it on i18n.
Moved pigment colors of blocks and items to tooltips.

### CODE REVIEW

**Comment by 3TUSK** [comment]
I wonder if there is any chance to let [this](https://github.com/binnie567/Binnies-Mods-Localisation/pull/11) be part of this pull request? That pull request has been hanging there for almost two years.

**Comment by liach** [comment]
@3TUSK Guess you need to open another pull request.

**Comment by mezz** [comment]
I'll gladly pull your changes @3TUSK.

**Comment by mezz** [comment]
Please resolve conflicts before I can merge this.

**Comment by KorDum** [comment]
I resolved it.
@3TUSK check _botany/lang/en_US.lang_ for new lines please.

**Comment by mezz** [comment]
Looks good. I agree that putting the color on the tooltip instead of in the name makes sense.

**Comment by 3TUSK** [comment]
@KorDum Already included, so don't worry.

**Comment by KorDum** [comment]
@3TUSK In PR #59 (not merged yet) added some new lines.
And will be added even more with time :)

**Pull request merged**
