### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by KorDum**
Changes in `botany` package:
1. Reformat code
2. Removed useless `else` after `if` with `return`
3. Upper case for Enums (instead flower species yet)
4. Added missing localization for Soil Meter
5. Optimized imports
6. Removed useless `this`, `final`
7. Rename `coloUr` to `color`

Sorry for large changes.

### CODE REVIEW

**Comment by Nedelosk** [comment]
Can you please use the forestry settings if you Optimized imports. #123

**Review by Nedelosk — CHANGES_REQUESTED** [review]
Can you please remove "//TODO fix deprecated" in the block classes. Because there is currently no way to not use the deprecated versions.

**Comment by KorDum** [comment]
Thanks for review!
I fixed all issues.

**Review by Nedelosk — APPROVED** [review]

**Comment by Nedelosk** [comment]
@KorDum Can you please run it again with the new settings that I have uploaded to the ForestryMC repository. I have removed the tabs on blank lines.

**Comment by KorDum** [comment]
Done!

**Comment by Nedelosk** [comment]
Thanks

**Comment by mezz** [comment]
I don't think there is anything bad about using `this.` for accessing things.
The use of `final` is a bit excessive but it's not entirely wrong either. In some longer methods it can be helpful. I also find it helpful for methods that do math, so we know what variables will be changing and which will not.

**Comment by KorDum** [comment]
> I don't think there is anything bad about using this. for accessing things.

This makes sense in the constructors, where the argument with the same name as the member of the class.
Like this: https://github.com/ForestryMC/ForestryMC/blob/mc-1.11/src/main/java/forestry/core/items/DrinkProperties.java
In the constructor uses `this`, and without in getters.

**Comment by mezz** [comment]
Ok, that's fine. What about `final`?

**Comment by KorDum** [comment]
> What about final?

> I also find it helpful for methods that do math, so we know what variables will be changing and which will not.

I agree with this. But `final` is redundant in method signature, what do you think?

**Comment by mezz** [comment]
It is bad practice to reassign method parameters, I'm ok with removing `final` from them there because that convention is strong already.

**Comment by KorDum** [comment]
`final` was automatically inserted by the compiler (by optimization), I think. And the decompiler returned it everywhere.
Return the "final" back wherever it was removed?

**Comment by mezz** [comment]
I guess it's fine without. We can add them back if we run into places where we need them.

**Review by mezz — APPROVED** [review]

**Pull request merged**
