### PR TITLE
AlcoholDrinking correct implementation

### PR DESCRIPTION
**Pull request by RusTit**
The current implementation does not work at all.
After drinking (actually eating) the item disappeared.
I made an implementation based on the ItemFood source code
Please check carefully for possible errors.

### CODE REVIEW

**Comment by RusTit** [comment]
Finally, you can get drunk =)
P.S. it was possible before too, but complicated, because of item disappearing.

**Comment by RusTit** [comment]
https://github.com/ForestryMC/Binnie/blob/6fa570987ac9a73cd6dbb205f06dc8d0de70ca6c/extratrees/src/main/java/binnie/extratrees/items/ItemDrink.java#L49
By the way, it seems to me that this is incorrect (and not convenient).
Maybe it should be 64?

**Comment by mezz** [comment]
I don't think drinking a stack of alcohol is a good idea, holding 1 glass and refilling it from a source of alcohol makes sense to me. :)

**Comment by RusTit** [comment]
Ok =)

**Comment by mezz** [comment]
Fluid handlers also become more tricky when there is more than 1 item per stack, since you just want to drain one at a time. This code would become a bit more complex.

**Pull request merged**
