### PR TITLE
Fix #140

### LINKED ISSUE #140: [1.7.10] Invalid Botany color Alleles
`Missing: {UID1:"botany.colorKhaki",UID0:"botany.colorKhaki",Slot:1b}`
And more colors
https://pastebin.com/raw/nSUT8kqK

### PR DESCRIPTION
**Pull request by KorDum**
#140 
Fix invalid allele color

### CODE REVIEW

**Comment by KorDum** [comment]
@mezz can you build and publish new version?

**Comment by mezz** [comment]
Sure

**Comment by mezz** [comment]
pre16: https://minecraft.curseforge.com/projects/binnies-mods/files/2440605

**Comment by KorDum** [comment]
Thanks!

**Pull request merged**
