### PR TITLE
Fix #366

### LINKED ISSUE #366: Wooden Tiles
Minecraft: 1.12.2
Forge: 2556
Mods: [list.txt](https://github.com/ForestryMC/Binnie/files/1540629/list.txt)

### PR DESCRIPTION
**Pull request by RusTit**
The main thing is that this pull request fixes issue #366 
1. While rotating the block face up and down, the bottom part rotates in the opposite direction from the top.
2. There were also problems in synchronizing the parts during the remaining rotations, especially the bottom.
3. I allowed myself a little to refactor and optimize EnumDesign (the last two commits).

### CODE REVIEW

**Comment by mezz** [comment]
Thanks for contributing!
This will take some time to review, there are a lot of patterns to try.
Could you include some screenshots to show the improved behavior, and to see that the patterns work correctly?

**Comment by RusTit** [comment]
UP faced:
Before:


After:

**Comment by RusTit** [comment]
BOTTOM faced (I don't rotated blocks from prev. scr., just changed facing direction - shift+click)
Before:


After:

**Comment by RusTit** [comment]
EAST faced:
Before:

After:

**Comment by KorDum** [comment]
And what about the hammer in your hand? :)

**Comment by RusTit** [comment]
Ha, I did not pay attention before, I do not know =)

**Comment by RusTit** [comment]
I checked now the moment in the glitch texture Hammer (though on another computer), everything is normal, strange.

**Comment by RusTit** [comment]
My thoughts about the model of the hammer:
1. It seems to me that this is the problem of my particular PC (apparently because of the driver for the video).
2. In fact, I have a bug in the master branch.
3. It's funny that during any movement (rolling, rotating) the model is drawn completely.

4. During the rest (standing still), the bug is constant.

**Comment by mezz** [comment]
Thank you, looks good to me. 
I haven't seen that hammer glitch before, interesting. Maybe open a bug for it if you can find out the reason.

**Pull request merged**
