### PR TITLE
Code cleanup extrabees

### PR DESCRIPTION
**Pull request by RusTit**

### CODE REVIEW

**Comment by RusTit** [comment]
@mezz Please review this:
https://github.com/ForestryMC/Binnie/blob/a34b9047561d8885dd546cec243464ac564a8b9c/extrabees/src/main/java/binnie/extrabees/items/ItemHoneyCrystal.java#L93
`1.0D / 0.0`
How to fix?

**Comment by Nedelosk** [comment]
Replace `1.0D / 0.0` with `Double.POSITIVE_INFINITY`.

**Comment by Nedelosk** [comment]
And you could replace `2147483647` with `Integer.MAX_VALUE`.

**Comment by RusTit** [comment]
Done

**Pull request merged**
