### PR TITLE
Tree generation code rewrite

### LINKED ISSUE #278: [1.12.1] Trees with a 2x2 or higher girth don't spawn correctly
Saplings from Extra Trees with a 2x2 or higher girth don't spawn correctly, this happens if the sapling has the higher girth normally or if you change via serum or the genesis item.

They will for some reason spawn correctly if you use bone meal on the sapling in the N-W conner, for 2x2, but if you use the bone meal on any other sapling they won't spawn correctly.

- Minecraft : 1.12.1
- Forge : 14.22.0.2456
- Forestry :1.12-5.5.0.169
- Binnie : 1.12-2.3.0.32

### LINKED ISSUE #608: Banana Trees don't grow their produce
Pack: A Bit of Everything 3.4.0
Version of Forestry: 5.8.2.387
Version of Binnie's Mods: 2.5.1.188
As stated in the title, Banana trees don't grow their produce. Things I have tried to use to make them grow their produce: used a supremium watering can and put the trees into a forestry multifarm set to orchard mode.

### PR DESCRIPTION
**Pull request by nstearns96**
Cleaned up import
Fixed pod textures
Downgraded Forestry version
Fixed trees not generating pods (Fixes: #608 )
Fixed trees with 2x2 or more girth not generating correctly (Fixes: #278 )

I apologize for the massive file change count, I optimized the imports using Intellij's automatic process which I think would be good to use going forward to keep the imports consistent

### CODE REVIEW

**Comment by mezz** [comment]
I will run optimize imports as a separate commit so that it is not included in this PR.

**Comment by mezz** [comment]
It looks like there are many conflicts because we do not use import with `*`.
I will update your branch to match.

**Comment by mezz** [comment]
This is still a lot to look over, can you provide screenshots to show the changes?

**Comment by nstearns96** [comment]
In the game, the only things that should have changed are the two issues I referenced. As far as the actual code base goes, this allows us to have total control over the trunk, leaves, and fruit pods of each tree type, which is what I wanted in order to change the appearance of the trees, which I have not yet done.

**Comment by mezz** [comment]
Ok, thanks. looks good to me

**Pull request merged**
