### PR TITLE
Improve code readability for binnie.core package

### PR DESCRIPTION
**Pull request by KorDum**
Improve code readability for _binnie.core_ package.
Minor refactoring of especially bad code.
Renaming method's parameters into an understandable form.
Drop useless casts.
Drop "final"-keyword after decompile.

### CODE REVIEW

**Comment by mezz** [comment]
Looks good. I think you should expand any `*` imports though, Forestry and Binnie's often name things with similar or the same name. With `*` import it's easier to accidentally use the wrong thing.

**Comment by KorDum** [comment]
Where did I miss expand imports? Or I don't understand?
Do you mean that I need to use
```
some.package.*;
```
instead
```
some.package.Class1;
some.package.Class2;
```
?

**Comment by mezz** [comment]
Right, you should replace any imports that use *, so that it shows all the imports.

**Comment by mezz** [comment]
That is the opposite of what you need to do, sorry. There should be no *.

**Comment by KorDum** [comment]
Done. Although I'm a supporter of fully qualified class names in imports, but I'm not dictating here code style :)

**Comment by KorDum** [comment]
Oh. Now I will return as it was.

**Comment by KorDum** [comment]
My Intellij IDEA replaced 5+ similar imports with `*`. I've сhanged its settings.

**Comment by mezz** [comment]
Cool, looks good.

**Pull request merged**
