### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by KorDum**
Some refactoring.
Added some localizations.

### CODE REVIEW

**Comment by mezz** [comment]
Looks good.
Will you be looking over the 1.11.2 branch later?

**Comment by KorDum** [comment]
Thanks! Do you invite me? ;)
Maybe. While I would like to translate the mod, remove the critical bugs and use on my server.
I'm not so familiar with version 1.11.2, but I can try looking over in free time :)

**Comment by mezz** [comment]
Ok, you have been added to the team!
The translation issues on 1.11.2 will probably be the same.

**Comment by KorDum** [comment]
Thanks!
I will make the same small commits in 1.11.2 with translate fixes later.

**Comment by KorDum** [comment]
Can I get permissions for tags and issue assignment?

**Comment by mezz** [comment]
You will be able to once you accept the invitation, check your email.

**Pull request merged**
