### PR TITLE
Fix #154

### LINKED ISSUE #154: [1.7.10] Door is not dropped if breaks block below it
The door just disappears.

### PR DESCRIPTION
**Pull request by KorDum**
Fix #154
Fix door disappears if breaks block below

### CODE REVIEW

**Comment by KorDum** [comment]
Please code review

**Comment by mezz** [comment]
The code looks fine to me, the real question is if the door works well in the world. It just needs good testing.

**Comment by KorDum** [comment]
@mezz I tested these changes in sigle and multiplayer.
Synchronization of the door status between 2+ clients.
Correctly drops out the right door if you break (harvest) it from top or bottom block.
And Correctly drops out the right door if you break under block.

**Comment by mezz** [comment]
Sounds good to me.

**Comment by KorDum** [comment]
Then merge it?
Can you build and publish to Curse? :)

**Comment by mezz** [comment]
I can publish a new build this weekend

**Pull request merged**
