### PR TITLE
Lumbermill support for wood from other mods

### PR DESCRIPTION
**Pull request by lex1975**
Please add Lumbermill support for wood from other mods (TwilightForest, LOTR, Highlands, BoP etc.) or Minetweaker/Crafttweaker (Modtweaker) support.

### CODE REVIEW

**Comment by KorDum** [comment]
Please checkout to actually commit from master-1.7.10 and readd your changes.
Too many conflicts.

**Comment by KorDum** [comment]
> wants to merge 33 commits into master-MC**1.11.2** from master-MC**1.7.10**

Is this mistake?

**Comment by KorDum** [comment]
Is this issue (not PR) maybe?

**Comment by lex1975** [comment]
Sorry, I was wrong in formatting

**Pull request closed without merging**
